2024-12-31 12:27:20,442 | ERROR | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\byzzzzzovvvvvvv\PycharmProjects\pythonProject\tests_12_4.py", line 68, in test_run
    test_run = Runner(12.4)
               ^^^^^^^^^^^^
  File "C:\Users\byzzzzzovvvvvvv\PycharmProjects\pythonProject\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано float
2024-12-31 12:27:20,444 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\byzzzzzovvvvvvv\PycharmProjects\pythonProject\tests_12_4.py", line 58, in test_walk
    test_walk = Runner("test_obj_walk", speed=-5)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\byzzzzzovvvvvvv\PycharmProjects\pythonProject\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
